# Generated by Django 4.1.3 on 2022-12-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_useraddressbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddressbook',
            name='mobile',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
