# Generated by Django 4.1.3 on 2022-12-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_useraddressbook_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddressbook',
            name='mobile',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
